-- Criação do banco de dados para o sistema de agendamento médico
CREATE DATABASE clinica;

USE clinica;

-- Criação das tabelas

-- Convenio
CREATE TABLE convenio (
    cd_convenio NUMBER PRIMARY KEY,
    nm_convenio VARCHAR2(100) NOT NULL
);

-- Plano
CREATE TABLE plano (
    cd_plano NUMBER PRIMARY KEY,
    nm_plano VARCHAR2(100) NOT NULL,
    cd_convenio NUMBER NOT NULL,
    CONSTRAINT fk_plano_convenio FOREIGN KEY (cd_convenio) REFERENCES convenio(cd_convenio)
);

-- Paciente
CREATE TABLE paciente (
    cd_paciente NUMBER PRIMARY KEY,
    nm_paciente VARCHAR2(100) NOT NULL,
    tp_sexo CHAR(1) NOT NULL,
    tp_sangue VARCHAR2(3),
    cpf VARCHAR2(14) UNIQUE NOT NULL
);

-- Medico
CREATE TABLE medico (
    cd_medico NUMBER PRIMARY KEY,
    nm_medico VARCHAR2(100) NOT NULL,
    tp_sexo CHAR(1) NOT NULL
);

-- Especialidade
CREATE TABLE especialidade (
    cd_especialidade NUMBER PRIMARY KEY,
    nm_especialidade VARCHAR2(100) NOT NULL
);

-- Especialidade_Medico
CREATE TABLE especialidade_medico (
    cd_medico NUMBER NOT NULL,
    cd_especialidade NUMBER NOT NULL,
    CONSTRAINT pk_especialidade_medico PRIMARY KEY (cd_medico, cd_especialidade),
    CONSTRAINT fk_em_medico FOREIGN KEY (cd_medico) REFERENCES medico(cd_medico),
    CONSTRAINT fk_em_especialidade FOREIGN KEY (cd_especialidade) REFERENCES especialidade(cd_especialidade)
);

-- Carteira
CREATE TABLE carteira (
    cd_paciente NUMBER NOT NULL,
    cd_plano NUMBER NOT NULL,
    CONSTRAINT pk_carteira PRIMARY KEY (cd_paciente, cd_plano),
    CONSTRAINT fk_carteira_paciente FOREIGN KEY (cd_paciente) REFERENCES paciente(cd_paciente),
    CONSTRAINT fk_carteira_plano FOREIGN KEY (cd_plano) REFERENCES plano(cd_plano)
);

-- Agenda
CREATE TABLE agenda (
    cd_agenda NUMBER PRIMARY KEY,
    cd_paciente NUMBER NOT NULL,
    cd_medico NUMBER NOT NULL,
    dt_agenda DATE NOT NULL,
    tp_atendimento VARCHAR2(20),
    CONSTRAINT fk_agenda_paciente FOREIGN KEY (cd_paciente) REFERENCES paciente(cd_paciente),
    CONSTRAINT fk_agenda_medico FOREIGN KEY (cd_medico) REFERENCES medico(cd_medico)
);

-- Log_Agenda (para trigger)
CREATE TABLE log_agenda (
    id_log NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operacao VARCHAR2(10),
    cd_agenda NUMBER,
    data_operacao DATE DEFAULT SYSDATE
);

-- Sequence para paciente (Parte 7)
CREATE SEQUENCE seq_paciente START WITH 1 INCREMENT BY 1;