-- Impedir agendamento com data passada
ALTER TABLE agenda
ADD CONSTRAINT ck_agenda_data_atual CHECK (dt_agenda >= SYSDATE);

-- Paciente precisa ter carteira (exceto particular)
-- Regra implementada via TRIGGER, pois depende de outra tabela
CREATE OR REPLACE TRIGGER tg_paciente_carteira
BEFORE INSERT ON agenda
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    IF :NEW.tp_atendimento <> 'PARTICULAR' THEN
        SELECT COUNT(*) INTO v_count FROM carteira WHERE cd_paciente = :NEW.cd_paciente;
        IF v_count = 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Paciente precisa ter carteira para este atendimento.');
        END IF;
    END IF;
END;
/

-- Impedir agendamento duplicado no mesmo horário para o mesmo paciente
ALTER TABLE agenda
ADD CONSTRAINT un_paciente_horario UNIQUE (cd_paciente, dt_agenda);

-- Garantir que apenas médicos cadastrados podem ser agendados
ALTER TABLE agenda
ADD CONSTRAINT fk_agenda_medico2 FOREIGN KEY (cd_medico) REFERENCES medico(cd_medico);


-- VIEW com médico, especialidade, paciente, convênio e data/hora
CREATE OR REPLACE VIEW vw_agenda_completa AS
SELECT m.nm_medico,
       e.nm_especialidade,
       p.nm_paciente,
       c.cd_convenio,
       a.dt_agenda
FROM agenda a
JOIN medico m ON m.cd_medico = a.cd_medico
JOIN especialidade_medico em ON em.cd_medico = m.cd_medico
JOIN especialidade e ON e.cd_especialidade = em.cd_especialidade
JOIN paciente p ON p.cd_paciente = a.cd_paciente
LEFT JOIN carteira c ON c.cd_paciente = p.cd_paciente;


-- TRIGGER de log de alterações em agenda
CREATE TABLE log_agenda (
    id_log NUMBER GENERATED BY DEFAULT AS IDENTITY,
    operacao VARCHAR2(10),
    cd_agenda NUMBER,
    data_operacao DATE DEFAULT SYSDATE
);

CREATE OR REPLACE TRIGGER tg_log_agenda
AFTER INSERT OR UPDATE OR DELETE ON agenda
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO log_agenda (operacao, cd_agenda) VALUES ('INSERT', :NEW.cd_agenda);
    ELSIF UPDATING THEN
        INSERT INTO log_agenda (operacao, cd_agenda) VALUES ('UPDATE', :NEW.cd_agenda);
    ELSIF DELETING THEN
        INSERT INTO log_agenda (operacao, cd_agenda) VALUES ('DELETE', :OLD.cd_agenda);
    END IF;
END;
/

-- VIEW de quantidade de consultas por médico
CREATE OR REPLACE VIEW vw_qtde_consultas_medico AS
SELECT cd_medico, COUNT(*) AS total_consultas
FROM agenda
GROUP BY cd_medico;

-- SEQUENCE para gerar código de paciente
CREATE SEQUENCE seq_paciente START WITH 1 INCREMENT BY 1;

-- PROCEDURE para listar horários disponíveis de um médico
CREATE OR REPLACE PROCEDURE pr_horarios_disponiveis(
    p_cd_medico IN NUMBER,
    p_data IN DATE
) AS
BEGIN
    SELECT * FROM agenda
    WHERE cd_medico = p_cd_medico
    AND TRUNC(dt_agenda) = TRUNC(p_data);
END;
/

-- VIEW percentual de pacientes por sexo
CREATE OR REPLACE VIEW vw_percentual_sexo AS
SELECT tp_sexo,
       ROUND((COUNT(*) / (SELECT COUNT(*) FROM paciente)) * 100, 2) AS percentual
FROM paciente
GROUP BY tp_sexo;